# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /ppp/mywebserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /ppp/mywebserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /ppp/mywebserver/CMakeFiles /ppp/mywebserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /ppp/mywebserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named echoserver

# Build rule for target.
echoserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echoserver
.PHONY : echoserver

# fast build rule for target.
echoserver/fast:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/build
.PHONY : echoserver/fast

#=============================================================================
# Target rules for targets named webclient

# Build rule for target.
webclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 webclient
.PHONY : webclient

# fast build rule for target.
webclient/fast:
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/build
.PHONY : webclient/fast

src/Acceptor.o: src/Acceptor.cpp.o

.PHONY : src/Acceptor.o

# target to build an object file
src/Acceptor.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Acceptor.cpp.o
.PHONY : src/Acceptor.cpp.o

src/Acceptor.i: src/Acceptor.cpp.i

.PHONY : src/Acceptor.i

# target to preprocess a source file
src/Acceptor.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Acceptor.cpp.i
.PHONY : src/Acceptor.cpp.i

src/Acceptor.s: src/Acceptor.cpp.s

.PHONY : src/Acceptor.s

# target to generate assembly for a file
src/Acceptor.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Acceptor.cpp.s
.PHONY : src/Acceptor.cpp.s

src/Buffer.o: src/Buffer.cpp.o

.PHONY : src/Buffer.o

# target to build an object file
src/Buffer.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Buffer.cpp.o
.PHONY : src/Buffer.cpp.o

src/Buffer.i: src/Buffer.cpp.i

.PHONY : src/Buffer.i

# target to preprocess a source file
src/Buffer.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Buffer.cpp.i
.PHONY : src/Buffer.cpp.i

src/Buffer.s: src/Buffer.cpp.s

.PHONY : src/Buffer.s

# target to generate assembly for a file
src/Buffer.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Buffer.cpp.s
.PHONY : src/Buffer.cpp.s

src/Channel.o: src/Channel.cpp.o

.PHONY : src/Channel.o

# target to build an object file
src/Channel.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Channel.cpp.o
.PHONY : src/Channel.cpp.o

src/Channel.i: src/Channel.cpp.i

.PHONY : src/Channel.i

# target to preprocess a source file
src/Channel.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Channel.cpp.i
.PHONY : src/Channel.cpp.i

src/Channel.s: src/Channel.cpp.s

.PHONY : src/Channel.s

# target to generate assembly for a file
src/Channel.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Channel.cpp.s
.PHONY : src/Channel.cpp.s

src/Connection.o: src/Connection.cpp.o

.PHONY : src/Connection.o

# target to build an object file
src/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Connection.cpp.o
.PHONY : src/Connection.cpp.o

src/Connection.i: src/Connection.cpp.i

.PHONY : src/Connection.i

# target to preprocess a source file
src/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Connection.cpp.i
.PHONY : src/Connection.cpp.i

src/Connection.s: src/Connection.cpp.s

.PHONY : src/Connection.s

# target to generate assembly for a file
src/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Connection.cpp.s
.PHONY : src/Connection.cpp.s

src/DefaultPoller.o: src/DefaultPoller.cpp.o

.PHONY : src/DefaultPoller.o

# target to build an object file
src/DefaultPoller.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/DefaultPoller.cpp.o
.PHONY : src/DefaultPoller.cpp.o

src/DefaultPoller.i: src/DefaultPoller.cpp.i

.PHONY : src/DefaultPoller.i

# target to preprocess a source file
src/DefaultPoller.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/DefaultPoller.cpp.i
.PHONY : src/DefaultPoller.cpp.i

src/DefaultPoller.s: src/DefaultPoller.cpp.s

.PHONY : src/DefaultPoller.s

# target to generate assembly for a file
src/DefaultPoller.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/DefaultPoller.cpp.s
.PHONY : src/DefaultPoller.cpp.s

src/EchoServer.o: src/EchoServer.cpp.o

.PHONY : src/EchoServer.o

# target to build an object file
src/EchoServer.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/EchoServer.cpp.o
.PHONY : src/EchoServer.cpp.o

src/EchoServer.i: src/EchoServer.cpp.i

.PHONY : src/EchoServer.i

# target to preprocess a source file
src/EchoServer.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/EchoServer.cpp.i
.PHONY : src/EchoServer.cpp.i

src/EchoServer.s: src/EchoServer.cpp.s

.PHONY : src/EchoServer.s

# target to generate assembly for a file
src/EchoServer.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/EchoServer.cpp.s
.PHONY : src/EchoServer.cpp.s

src/EventLoop.o: src/EventLoop.cpp.o

.PHONY : src/EventLoop.o

# target to build an object file
src/EventLoop.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/EventLoop.cpp.o
.PHONY : src/EventLoop.cpp.o

src/EventLoop.i: src/EventLoop.cpp.i

.PHONY : src/EventLoop.i

# target to preprocess a source file
src/EventLoop.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/EventLoop.cpp.i
.PHONY : src/EventLoop.cpp.i

src/EventLoop.s: src/EventLoop.cpp.s

.PHONY : src/EventLoop.s

# target to generate assembly for a file
src/EventLoop.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/EventLoop.cpp.s
.PHONY : src/EventLoop.cpp.s

src/HttpContext.o: src/HttpContext.cpp.o

.PHONY : src/HttpContext.o

# target to build an object file
src/HttpContext.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/HttpContext.cpp.o
.PHONY : src/HttpContext.cpp.o

src/HttpContext.i: src/HttpContext.cpp.i

.PHONY : src/HttpContext.i

# target to preprocess a source file
src/HttpContext.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/HttpContext.cpp.i
.PHONY : src/HttpContext.cpp.i

src/HttpContext.s: src/HttpContext.cpp.s

.PHONY : src/HttpContext.s

# target to generate assembly for a file
src/HttpContext.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/HttpContext.cpp.s
.PHONY : src/HttpContext.cpp.s

src/HttpResponse.o: src/HttpResponse.cpp.o

.PHONY : src/HttpResponse.o

# target to build an object file
src/HttpResponse.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/HttpResponse.cpp.o
.PHONY : src/HttpResponse.cpp.o

src/HttpResponse.i: src/HttpResponse.cpp.i

.PHONY : src/HttpResponse.i

# target to preprocess a source file
src/HttpResponse.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/HttpResponse.cpp.i
.PHONY : src/HttpResponse.cpp.i

src/HttpResponse.s: src/HttpResponse.cpp.s

.PHONY : src/HttpResponse.s

# target to generate assembly for a file
src/HttpResponse.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/HttpResponse.cpp.s
.PHONY : src/HttpResponse.cpp.s

src/Logger.o: src/Logger.cpp.o

.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Logger.cpp.o
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Logger.cpp.i
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Logger.cpp.s
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/TcpServer.o: src/TcpServer.cpp.o

.PHONY : src/TcpServer.o

# target to build an object file
src/TcpServer.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/TcpServer.cpp.o
.PHONY : src/TcpServer.cpp.o

src/TcpServer.i: src/TcpServer.cpp.i

.PHONY : src/TcpServer.i

# target to preprocess a source file
src/TcpServer.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/TcpServer.cpp.i
.PHONY : src/TcpServer.cpp.i

src/TcpServer.s: src/TcpServer.cpp.s

.PHONY : src/TcpServer.s

# target to generate assembly for a file
src/TcpServer.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/TcpServer.cpp.s
.PHONY : src/TcpServer.cpp.s

src/ThreadPool.o: src/ThreadPool.cpp.o

.PHONY : src/ThreadPool.o

# target to build an object file
src/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/ThreadPool.cpp.o
.PHONY : src/ThreadPool.cpp.o

src/ThreadPool.i: src/ThreadPool.cpp.i

.PHONY : src/ThreadPool.i

# target to preprocess a source file
src/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/ThreadPool.cpp.i
.PHONY : src/ThreadPool.cpp.i

src/ThreadPool.s: src/ThreadPool.cpp.s

.PHONY : src/ThreadPool.s

# target to generate assembly for a file
src/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/ThreadPool.cpp.s
.PHONY : src/ThreadPool.cpp.s

src/Timestamp.o: src/Timestamp.cpp.o

.PHONY : src/Timestamp.o

# target to build an object file
src/Timestamp.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Timestamp.cpp.o
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/src/Timestamp.cpp.o
.PHONY : src/Timestamp.cpp.o

src/Timestamp.i: src/Timestamp.cpp.i

.PHONY : src/Timestamp.i

# target to preprocess a source file
src/Timestamp.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Timestamp.cpp.i
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/src/Timestamp.cpp.i
.PHONY : src/Timestamp.cpp.i

src/Timestamp.s: src/Timestamp.cpp.s

.PHONY : src/Timestamp.s

# target to generate assembly for a file
src/Timestamp.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Timestamp.cpp.s
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/src/Timestamp.cpp.s
.PHONY : src/Timestamp.cpp.s

src/Webserver.o: src/Webserver.cpp.o

.PHONY : src/Webserver.o

# target to build an object file
src/Webserver.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Webserver.cpp.o
.PHONY : src/Webserver.cpp.o

src/Webserver.i: src/Webserver.cpp.i

.PHONY : src/Webserver.i

# target to preprocess a source file
src/Webserver.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Webserver.cpp.i
.PHONY : src/Webserver.cpp.i

src/Webserver.s: src/Webserver.cpp.s

.PHONY : src/Webserver.s

# target to generate assembly for a file
src/Webserver.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/Webserver.cpp.s
.PHONY : src/Webserver.cpp.s

src/epoll.o: src/epoll.cpp.o

.PHONY : src/epoll.o

# target to build an object file
src/epoll.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/epoll.cpp.o
.PHONY : src/epoll.cpp.o

src/epoll.i: src/epoll.cpp.i

.PHONY : src/epoll.i

# target to preprocess a source file
src/epoll.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/epoll.cpp.i
.PHONY : src/epoll.cpp.i

src/epoll.s: src/epoll.cpp.s

.PHONY : src/epoll.s

# target to generate assembly for a file
src/epoll.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/epoll.cpp.s
.PHONY : src/epoll.cpp.s

src/inetAddress.o: src/inetAddress.cpp.o

.PHONY : src/inetAddress.o

# target to build an object file
src/inetAddress.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/inetAddress.cpp.o
.PHONY : src/inetAddress.cpp.o

src/inetAddress.i: src/inetAddress.cpp.i

.PHONY : src/inetAddress.i

# target to preprocess a source file
src/inetAddress.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/inetAddress.cpp.i
.PHONY : src/inetAddress.cpp.i

src/inetAddress.s: src/inetAddress.cpp.s

.PHONY : src/inetAddress.s

# target to generate assembly for a file
src/inetAddress.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/inetAddress.cpp.s
.PHONY : src/inetAddress.cpp.s

src/poller.o: src/poller.cpp.o

.PHONY : src/poller.o

# target to build an object file
src/poller.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/poller.cpp.o
.PHONY : src/poller.cpp.o

src/poller.i: src/poller.cpp.i

.PHONY : src/poller.i

# target to preprocess a source file
src/poller.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/poller.cpp.i
.PHONY : src/poller.cpp.i

src/poller.s: src/poller.cpp.s

.PHONY : src/poller.s

# target to generate assembly for a file
src/poller.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/poller.cpp.s
.PHONY : src/poller.cpp.s

src/socket.o: src/socket.cpp.o

.PHONY : src/socket.o

# target to build an object file
src/socket.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/socket.cpp.o
.PHONY : src/socket.cpp.o

src/socket.i: src/socket.cpp.i

.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/socket.cpp.i
.PHONY : src/socket.cpp.i

src/socket.s: src/socket.cpp.s

.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/socket.cpp.s
.PHONY : src/socket.cpp.s

src/sql_connection_pool.o: src/sql_connection_pool.cpp.o

.PHONY : src/sql_connection_pool.o

# target to build an object file
src/sql_connection_pool.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/sql_connection_pool.cpp.o
.PHONY : src/sql_connection_pool.cpp.o

src/sql_connection_pool.i: src/sql_connection_pool.cpp.i

.PHONY : src/sql_connection_pool.i

# target to preprocess a source file
src/sql_connection_pool.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/sql_connection_pool.cpp.i
.PHONY : src/sql_connection_pool.cpp.i

src/sql_connection_pool.s: src/sql_connection_pool.cpp.s

.PHONY : src/sql_connection_pool.s

# target to generate assembly for a file
src/sql_connection_pool.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/sql_connection_pool.cpp.s
.PHONY : src/sql_connection_pool.cpp.s

src/tcpepoll.o: src/tcpepoll.cpp.o

.PHONY : src/tcpepoll.o

# target to build an object file
src/tcpepoll.cpp.o:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/tcpepoll.cpp.o
.PHONY : src/tcpepoll.cpp.o

src/tcpepoll.i: src/tcpepoll.cpp.i

.PHONY : src/tcpepoll.i

# target to preprocess a source file
src/tcpepoll.cpp.i:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/tcpepoll.cpp.i
.PHONY : src/tcpepoll.cpp.i

src/tcpepoll.s: src/tcpepoll.cpp.s

.PHONY : src/tcpepoll.s

# target to generate assembly for a file
src/tcpepoll.cpp.s:
	$(MAKE) -f CMakeFiles/echoserver.dir/build.make CMakeFiles/echoserver.dir/src/tcpepoll.cpp.s
.PHONY : src/tcpepoll.cpp.s

src1/webclient.o: src1/webclient.cpp.o

.PHONY : src1/webclient.o

# target to build an object file
src1/webclient.cpp.o:
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/src1/webclient.cpp.o
.PHONY : src1/webclient.cpp.o

src1/webclient.i: src1/webclient.cpp.i

.PHONY : src1/webclient.i

# target to preprocess a source file
src1/webclient.cpp.i:
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/src1/webclient.cpp.i
.PHONY : src1/webclient.cpp.i

src1/webclient.s: src1/webclient.cpp.s

.PHONY : src1/webclient.s

# target to generate assembly for a file
src1/webclient.cpp.s:
	$(MAKE) -f CMakeFiles/webclient.dir/build.make CMakeFiles/webclient.dir/src1/webclient.cpp.s
.PHONY : src1/webclient.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... echoserver"
	@echo "... webclient"
	@echo "... src/Acceptor.o"
	@echo "... src/Acceptor.i"
	@echo "... src/Acceptor.s"
	@echo "... src/Buffer.o"
	@echo "... src/Buffer.i"
	@echo "... src/Buffer.s"
	@echo "... src/Channel.o"
	@echo "... src/Channel.i"
	@echo "... src/Channel.s"
	@echo "... src/Connection.o"
	@echo "... src/Connection.i"
	@echo "... src/Connection.s"
	@echo "... src/DefaultPoller.o"
	@echo "... src/DefaultPoller.i"
	@echo "... src/DefaultPoller.s"
	@echo "... src/EchoServer.o"
	@echo "... src/EchoServer.i"
	@echo "... src/EchoServer.s"
	@echo "... src/EventLoop.o"
	@echo "... src/EventLoop.i"
	@echo "... src/EventLoop.s"
	@echo "... src/HttpContext.o"
	@echo "... src/HttpContext.i"
	@echo "... src/HttpContext.s"
	@echo "... src/HttpResponse.o"
	@echo "... src/HttpResponse.i"
	@echo "... src/HttpResponse.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/TcpServer.o"
	@echo "... src/TcpServer.i"
	@echo "... src/TcpServer.s"
	@echo "... src/ThreadPool.o"
	@echo "... src/ThreadPool.i"
	@echo "... src/ThreadPool.s"
	@echo "... src/Timestamp.o"
	@echo "... src/Timestamp.i"
	@echo "... src/Timestamp.s"
	@echo "... src/Webserver.o"
	@echo "... src/Webserver.i"
	@echo "... src/Webserver.s"
	@echo "... src/epoll.o"
	@echo "... src/epoll.i"
	@echo "... src/epoll.s"
	@echo "... src/inetAddress.o"
	@echo "... src/inetAddress.i"
	@echo "... src/inetAddress.s"
	@echo "... src/poller.o"
	@echo "... src/poller.i"
	@echo "... src/poller.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... src/sql_connection_pool.o"
	@echo "... src/sql_connection_pool.i"
	@echo "... src/sql_connection_pool.s"
	@echo "... src/tcpepoll.o"
	@echo "... src/tcpepoll.i"
	@echo "... src/tcpepoll.s"
	@echo "... src1/webclient.o"
	@echo "... src1/webclient.i"
	@echo "... src1/webclient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

